services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/myFirstDatabase 
      - MONGO_DB=myFirstDatabase
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
    depends_on:
      - mongodb
    command: ["python", "main.py"]
  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - ./storage:/data/db